# MachinaCore configuration file for customizing fuel burn times and block properties.
#
# The values specified here can override built-in defaults, specify new fuels or additional block properties.
# For an overview of all ids in minecraft, see:
# http://www.minecraftwiki.net/wiki/Data_values
#
# fuels section: Specifies the burn time for an id in ticks (20 ticks = 1 second)
# blocks section: Specifies the following block properties per id.
#  Built-in defaults will sometimes differ from the global defaults given below.
#  It is recommended to only define properties that you know you want to change.
#     solid: <boolean> - default: false - Whether the block is solid, meaning a machina could rest on it.
#     drillable: <boolean> - default: false - Whether the block can be drilled.
#     drillTime: <integer> - default: 1 - The number of ticks it takes to drill this block.
#     drop: <integer> - default: -1 - The item id to drop when this block is broken. Default is to use the block's own id, a value of 0 means drop nothing.
#     data: <integer> - default: -1 - The data value to set for the item dropped. Default is to use the block's data value.
#     dropMin: <integer> - default: 1 - The minimum amount to drop. If less than 1, nothing will be dropped unless dropRandom causes the result to be above 0.
#     dropRandom: <integer> - default: 0 - A random amount (0 to dropRandom-1) to add to dropMin.
#     copyData: <boolean> - default: false - (ADVANCED) Whether to preserve the block's data value when moving as part of a machina.
#     hasInventory: <boolean> - default: false - (ADVANCED) Whether the block has an inventory that should be preserved when moving as part of a machina.
#     attached: <boolean> - default: false - (ADVANCED) Whether the block can only exist attached to another block. (levers, ladders, rails, doors, etc)
#
# To provide a shorthand way to make many blocks non-breakable by drills, a list of ids can be given to the drill-block list.
#
# Example configuration that changes some properties for wooden planks, and blocks some man-made objects from being drilled:
#fuels:
#    5: 800
#blocks:
#    drill-block: [4, 5, 43, 44, 53]
#    5:
#        solid: false
#        drillable: false