name: MachinaRedstoneBridge
main: me.lyneira.MachinaRedstoneBridge.MachinaRedstoneBridge
version: @VERSION@
description: Allows a machina to be activated through a redstone signal.
author: Lyneira
website: http://dev.bukkit.org/server-mods/machinacraft/
dev-url: http://dev.bukkit.org/server-mods/machinacraft/
depend: [MachinaCore]